package com.vaanisathi.ui

import android.content.Intent
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.PictureAsPdf
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.FileProvider
import com.vaanisathi.db.FLNPhrase
import com.vaanisathi.db.VaaniSathiDatabase
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun WorksheetScreen(onBack: () -> Unit) {
    val context = LocalContext.current
    val db = remember { VaaniSathiDatabase.getInstance(context) }
    val scope = rememberCoroutineScope()

    var phrases by remember { mutableStateOf<List<FLNPhrase>>(emptyList()) }
    var isGenerating by remember { mutableStateOf(false) }
    var generated by remember { mutableStateOf(false) }
    var pdfPath by remember { mutableStateOf("") }

    LaunchedEffect(Unit) {
        phrases = db.phraseDao().getAllPhrases()
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Column {
                        Text("NIPUN Worksheet Generator",
                            color = Color.White, fontWeight = FontWeight.Bold)
                        Text("Offline Printable Bilingual Worksheets",
                            color = Color.White.copy(alpha = 0.8f), fontSize = 11.sp)
                    }
                },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, "Back", tint = Color.White)
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = NavyBlue)
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .background(Color(0xFFF8FAFF))
                .padding(16.dp)
        ) {
            // Header card
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = Color(0xFFEFF6FF)),
                shape = RoundedCornerShape(16.dp)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text(
                        "📄 NIPUN Bharat Aligned Worksheet",
                        fontSize = 15.sp,
                        fontWeight = FontWeight.Bold,
                        color = NavyBlue
                    )
                    Spacer(Modifier.height(4.dp))
                    Text(
                        "Generated offline for Grades 1–3 tribal classrooms. Includes Hindi, Santhali Roman, and Ol Chiki script.",
                        fontSize = 12.sp,
                        color = Color(0xFF475569)
                    )
                    Spacer(Modifier.height(12.dp))
                    Button(
                        onClick = {
                            isGenerating = true
                            scope.launch(Dispatchers.IO) {
                                try {
                                    val fileName = "VaaniSathi_NIPUN_Worksheet.pdf"
                                    val file = File(
                                        context.getExternalFilesDir(null), fileName)

                                    val writer = PdfDocument()
                                    val pageInfo = PdfDocument
                                        .PageInfo.Builder(595, 842, 1).create()
                                    val page = writer.startPage(pageInfo)
                                    val canvas = page.canvas
                                    val paint = Paint().apply {
                                        textSize = 16f
                                        isFakeBoldText = true
                                    }
                                    canvas.drawText("VaaniSathi — NIPUN Bharat Worksheet", 40f, 50f, paint)
                                    paint.isFakeBoldText = false
                                    paint.textSize = 12f
                                    canvas.drawText("Hindi ↔ Santhali (Ol Chiki) | Grade 1–3", 40f, 75f, paint)

                                    var y = 110f
                                    paint.isFakeBoldText = true
                                    canvas.drawText("Hindi", 40f, y, paint)
                                    canvas.drawText("Roman", 200f, y, paint)
                                    canvas.drawText("Ol Chiki", 380f, y, paint)
                                    paint.isFakeBoldText = false
                                    y += 20f

                                    for (p in phrases) {
                                        if (y > 800f) break
                                        canvas.drawText(p.hindiText, 40f, y, paint)
                                        canvas.drawText(p.santhaliRoman, 200f, y, paint)
                                        canvas.drawText(p.santhaliOlChiki, 380f, y, paint)
                                        y += 22f
                                    }

                                    writer.finishPage(page)
                                    val fos = FileOutputStream(file)
                                    writer.writeTo(fos)
                                    writer.close()
                                    fos.close()

                                    // Share the PDF
                                    val uri = FileProvider.getUriForFile(
                                        context,
                                        "${context.packageName}.provider",
                                        file
                                    )
                                    val intent = Intent(
                                        Intent.ACTION_VIEW).apply {
                                        setDataAndType(uri, "application/pdf")
                                        addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                                    }

                                    withContext(Dispatchers.Main) {
                                        isGenerating = false
                                        pdfPath = file.absolutePath
                                        generated = true
                                        context.startActivity(
                                            Intent.createChooser(
                                            intent, "Open or Save PDF"))
                                    }
                                } catch (e: Exception) {
                                    withContext(Dispatchers.Main) {
                                        isGenerating = false
                                        Toast.makeText(context, "Error: ${e.message}",
                                            Toast.LENGTH_LONG).show()
                                    }
                                }
                            }
                        },
                        colors = ButtonDefaults.buttonColors(containerColor = SaffronOrange),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Icon(Icons.Default.PictureAsPdf, contentDescription = "PDF", tint = Color.White)
                        Spacer(Modifier.width(8.dp))
                        Text(
                            if (isGenerating) "Generating PDF..." else "Generate & Export PDF Worksheet",
                            fontWeight = FontWeight.Bold,
                            color = Color.White
                        )
                    }

                    if (generated) {
                        Spacer(Modifier.height(8.dp))
                        Text(
                            "✅ Saved: $pdfPath",
                            fontSize = 11.sp,
                            color = ForestGreen,
                            fontWeight = FontWeight.Medium
                        )
                    }
                }
            }

            Spacer(Modifier.height(16.dp))

            Text(
                "Preview: Bilingual Vocabulary Table (${phrases.size} Phrases)",
                fontSize = 13.sp,
                fontWeight = FontWeight.Bold,
                color = NavyBlue
            )
            Spacer(Modifier.height(8.dp))

            // Table preview
            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .weight(1f),
                colors = CardDefaults.cardColors(containerColor = Color.White),
                shape = RoundedCornerShape(12.dp)
            ) {
                LazyColumn(
                    modifier = Modifier
                        .fillMaxSize()
                        .padding(8.dp),
                    verticalArrangement = Arrangement.spacedBy(6.dp)
                ) {
                    item {
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .background(Color(0xFFE2E8F0))
                                .padding(8.dp),
                            horizontalArrangement = Arrangement.SpaceBetween
                        ) {
                            Text("Hindi", fontWeight = FontWeight.Bold, fontSize = 12.sp, modifier = Modifier.weight(1f))
                            Text("Roman", fontWeight = FontWeight.Bold, fontSize = 12.sp, modifier = Modifier.weight(1f))
                            Text("Ol Chiki", fontWeight = FontWeight.Bold, fontSize = 12.sp, modifier = Modifier.weight(1f))
                            Text("Code", fontWeight = FontWeight.Bold, fontSize = 11.sp, textAlign = TextAlign.End, modifier = Modifier.weight(0.8f))
                        }
                    }
                    items(phrases) { p ->
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(vertical = 6.dp, horizontal = 4.dp),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(p.hindiText, fontSize = 12.sp, fontWeight = FontWeight.Medium, color = NavyBlue, modifier = Modifier.weight(1f))
                            Text(p.santhaliRoman, fontSize = 12.sp, color = Color(0xFF64748B), modifier = Modifier.weight(1f))
                            Text(p.santhaliOlChiki, fontSize = 14.sp, fontWeight = FontWeight.Bold, color = ForestGreen, modifier = Modifier.weight(1f))
                            Text(p.nipunCode, fontSize = 10.sp, color = Color.Gray, textAlign = TextAlign.End, modifier = Modifier.weight(0.8f))
                        }
                        HorizontalDivider(color = Color(0xFFF1F5F9))
                    }
                }
            }
        }
    }
}
